### PR TITLE
Milestone: DDL Commands and Normalization

### PR DESCRIPTION
**Pull request by tanishqpati**
Explanation of DDL commands concept: https://vimeo.com/872598759/f93f781f20
Explanation of Normalization concept: https://vimeo.com/872631480/9ef0e7d8cf

### CODE REVIEW

**Comment by th3c0d3br34ker** [comment]
thanks @Tanishqpati for you submission. the self-viva is satisfactory for `DDL Commands` and `Relational Data Model and Normalization`.

however a demo is missing, please attach that link and re-submit it.

thanks

**Comment by tanishqpati** [comment]
> thanks @Tanishqpati for you submission. the self-viva is satisfactory for `DDL Commands` and `Relational Data Model and Normalization`.
> 
> however a demo is missing, please attach that link and re-submit it.
> 
> thanks

Thanks Jainam @th3c0d3br34ker for the review. Here's the link of demo video: https://www.loom.com/share/24b32b695a8144eea8420012e49d7f67?sid=69387cba-2a52-44db-81cc-5b765e023b67

**Comment by th3c0d3br34ker** [comment]
hi @Tanishqpati please schedule a viva. The link for the same is available in the wiki.

**Comment by th3c0d3br34ker** [comment]
approved during viva. please consider the points discussed in mind for up coming milestones. 

please go ahead and merge this PR.

**Review by th3c0d3br34ker — APPROVED** [review]

**Pull request merged**
